### ISSUE TITLE
ui_gazergui.h is missing

### ISSUE THREAD

**Issue by herbstop** [lschilli/gazetool#5]
Required by gazergui.cpp

**Comment by lschilli** [comment]
`ui_gazergui.h` is not included in the source because it is an automatically generated header file.
`QT5_WRAP_UI(UI_HEADERS gazergui.ui)` in `src/CMakeLists.txt` should be responsible for this. The automatically generated header file is then added to `GAZETOOL_SRC` by including `${UI_HEADERS}`.

The issue you created does not indicate the exact problem (e.g. build failed). Please provide more details if possible.
